smart:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 172.22.97.194
    port: 3306
    database: smart
    username: fate
    password: 123456
  ai:
    url: http://127.0.0.1:5000/talking
spring:
  redis:
    host: 172.22.97.194
    port: 6379
    database: 0